### ISSUE TITLE
마이페이지에서 X버튼 클릭할 경우 메인페이지로 렌더링하는 것이 좋아보임

### ISSUE THREAD

**Issue by gboycdw** [MZgaMeZone/gaMeZone#216]
http://gamezone.gomao9.com/mypage

**Comment by 02rynn** [comment]
음.. 그럼 마이페이지의 하위 메뉴에서 x를 하면 mypage 메인으로 가고 mypage 메인에서 x를 누르면 메인화면으로 가는것으로 변경하는게 좋을거같습니다!
