### ISSUE TITLE
[BE] response data의 통일성

### ISSUE THREAD

**Issue by uniqueeest** [MZgaMeZone/gaMeZone#222]
현재 데이터를 서버에서 받아올 때, 배열 형태 그대로 받아오기 때문에 통일성이 떨어진다고 생각함. 
```
{
"data": {},
"error": {}
}
```
위와 같은 형식으로 통일성 있게 데이터를 보내면 어떨지 의견 제시해봅니다.

**Comment by uniqueeest** [comment]
![image](https://github.com/MZgaMeZone/gaMeZone/assets/123538138/3c8e518a-b92f-4327-8c63-2a064acac59a)

아니면 그냥 responseData 그대로 사용해도 괜찮을지

**Comment by gboycdw** [comment]
RESTful API 규약에 따라 상황에 맞는 응답코드와 함께 데이터 혹은 에러를 전달하는 것을 권장하기 때문에,
response에 두 값을 모두 담는 것은 좋지 않은 방법인 것 같다고 생각됩니다.
백엔드에서 보내는 try catch문을 잘 정리하여 에러코드와 에러메시지를 잘 설정해 주는 방향으로 가는 게 어떨지~~
