### ISSUE TITLE
[FE] 두더지 게임 버그

### ISSUE THREAD

**Issue by uniqueeest** [MZgaMeZone/gaMeZone#249]
현재 두더지를 한 번만 클릭할 수 있게 되어있지 않은 것 같음. 그렇기 때문에 한 마리의 두더지를 여러 번 클릭해서 점수를 올릴 수 있음. 이 부분 수정이 필요해보입니다.

**Comment by ksknote** [comment]
두더지 클릭이벤트에 쓰로틀링 적용하여 여러번 때려도 한번만 이벤트 핸들러가 실행되도록 수정하였습니다.
1000ms간 같은 두더지를 여러번 때려도 한번만 실행되며, 같은 위치에서 새로운 두더지가 나왔을 때는 두더지id로 구분하여 새롭게 쓰로틀링이 적용됩니다.
