### ISSUE TITLE
커뮤니티 페이지 잔류 시 네트워트 탭에 요청이 계속 보내지고 있습니다.

### ISSUE THREAD

**Issue by gboycdw** [MZgaMeZone/gaMeZone#261]
![image](https://github.com/MZgaMeZone/gaMeZone/assets/59162652/78152447-15ad-41d7-8a17-1c3851382273)

메소드에 oid가 노출되고 있고, 이유를 알 수 없지만 GET 요청이 계속해서 보내지고 있습니다.

무한루프 문제가 있을 수 있으니 관련 코드를 확인해볼 필요성이 있을 것 같습니다.

**Comment by gboycdw** [comment]
요청 url을 보니 get 메소드로 post 요청과 관련된 작업을 하려는 것으로 보임

**Comment by uniqueeest** [comment]
useEffect로 post를 받아오는 부분에서 deps 설정을 해놓지 않았습니다. 해당 부분 수정했습니다.
